### ISSUE TITLE
关于如何解决Notes根据页面 `Scroll & Change` 重新刷新的问题

### ISSUE THREAD

**Issue by BenBBear** [beenote-ucsd/beenote#17]
1. 由于页面HTML的互相耦合性， 不能只监听一部分页面。 因为**部分HTML的更改，可能导致整体页面的变化**。 因此基本思路为

    ```javascript
    obs = create_observer(document.body)
    obs.on_change(()=>{
	      refresh_all();
    })
    ```

2. 但这样刷新太快了， 性能会很低， 所以一个改进方案为： **设置最大刷新速率， 只在定点更新。**

3. 但 **定点更新** 又会带来一个问题， 就是*如果note在一个scrollable的区域， scrolling要求极高的刷新速率*， 而且还有一个问题没有被解决， 就是 *scrolling带来的notes partially visible问题*。 

4. 解决scrolling问题要采取的策略可能为： 
    a. 找到scrolling container
    b. 在container设置监听器， `onscroll(refresh_every_note_inside)`
    c. 并且计算 scrolling框 和每个note的关系， 来解决*notes partially visible问题*

5. 其他一些优化策略可以为
    a. 先比较 当前的bounding box和上一次的bounding box有没有改变
    b. 如果没有改变，则不刷新该note
    c. 此类轮询检查的操作可以在另一个thread中进行

**Comment by BenBBear** [comment]
判断Node是否有scrollBar方法之一

```js
 $.fn.hasScrollBar = function() {
    return this.get(0).scrollHeight > this.height();
  }
```

**Comment by BenBBear** [comment]
Succeed! 💯

**Comment by Vectorlee** [comment]
`var rect = element.getBoundingClientRect();
        var scrollHeight = element.scrollHeight;
        var scrollWidth = element.scrollWidth;

        if (scrollHeight > rect.height * 1.1 || scrollWidth > rect.width * 1.1) {
            return element;
        }`

**Comment by Vectorlee** [comment]
We judge the if it is a scroller by comparing the scrollHeight with the rect.Height, and we check if the scrollHeight is 1.1 bigger then the rect.Height

**Comment by BenBBear** [comment]
Problem considered solved, open new issues for solving scroller bugs
