### ISSUE TITLE
Better insertion point when right Click to create sticker

### ISSUE THREAD

**Issue by BenBBear** [beenote-ucsd/beenote#34]
Currently, right click will insert the note into current mouse location, but it seems the right click location should be the best spot. 

<img width="1440" alt="screen shot 2016-12-14 at 5 14 00 am" src="https://cloud.githubusercontent.com/assets/7659710/21157336/47c0edd0-c1bc-11e6-8911-fbe60c34f59e.png">

Also, maybe just use "Note" instead of "Create a sticker Note". Of course we will change the icon afterwards.

**Comment by Vectorlee** [comment]
fixed
